version: "3"
services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "8080:80"
        networks:
            - internal
        volumes:
            - ./:/var/www/html/
            - ./:/var/log/nginx/
        container_name: nginx
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        networks:
            - internal
        volumes:
            - ./:/var/www/html/
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./:/var/log/fpm-php.www.log
        container_name: php
        expose:
            - "9000"
    mysql:
        container_name: db
        restart: unless-stopped
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./db-data:/var/lib/mysql
        networks:
            - internal
networks:
    internal:
        driver: bridge
